services:
  portainer:
    image: portainer/portainer-ce:2.32.0
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
    volumes:
      - /home/blehnen/docker/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - socket_proxy
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.lab1830.com`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000 # <-- not 9443
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
networks:
  socket_proxy:
    external: true
  web:
    external: true
